import { A } from "@solidjs/router";
import { CalendarDays, Clock3, MapPin, Printer, Trophy, Users } from "lucide-solid";
import { For, Show } from "solid-js";
import { Badge, Button, Card, Text } from "~/components/ui";
import { useSoccerData } from "~/features/soccer/SoccerDataProvider";
import { SEGMENT_SECONDS } from "~/lib/soccer/fixed-game";
import { Box, Grid, HStack, VStack } from "styled-system/jsx";
import { PageHeader } from "./PageHeader";
export function DashboardPage() {
  const data = useSoccerData();
  const upcoming = () => [...(data.snapshot()?.games ?? [])].filter((game) => game.status === "scheduled").sort((a, b) => a.startsAt.localeCompare(b.startsAt))[0];
  const published = () => data.snapshot()?.schedules.filter((schedule) => schedule.status === "published") ?? [];
  const totalMinutes = (playerId: string) => published().flatMap((schedule) => schedule.assignments).filter((item) => item.playerId === playerId).length * SEGMENT_SECONDS / 60;
  return <><PageHeader eyebrow="Coach home" title="Next match, ready at a glance" description="Prepare a fair lineup, confirm every player, then carry one clear plan from the kitchen table to the sideline." actions={<HStack gap="2"><A href="/games"><Button variant="outline">View all games</Button></A><A href="/games/new"><Button>Plan a game</Button></A></HStack>}/>
    <Show when={upcoming()} fallback={<Card.Root><Card.Body><Text>No game is scheduled yet.</Text></Card.Body></Card.Root>}>{(game) => <Card.Root bg="grass.subtle.bg" borderColor="grass.subtle.border"><Card.Header><HStack justifyContent="space-between"><VStack alignItems="start" gap="2"><Badge colorPalette="grass">Next game</Badge><Card.Title textStyle="2xl">vs. {game().opponentName}</Card.Title><HStack gap="4" flexWrap="wrap" color="fg.muted"><HStack gap="1"><CalendarDays size={16}/>{new Date(game().startsAt).toLocaleString([], { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</HStack><HStack gap="1"><MapPin size={16}/>{game().venueName}</HStack></HStack></VStack><Trophy size={46}/></HStack></Card.Header><Card.Footer><HStack gap="2" flexWrap="wrap"><A href={`/games/${game().id}`}><Button>Review game plan</Button></A><A href={`/games/${game().id}/schedule`}><Button variant="outline">Open schedule</Button></A><A href={`/games/${game().id}/print`}><Button variant="plain"><Printer size={16}/> Print</Button></A></HStack></Card.Footer></Card.Root>}</Show>
    <Grid gridTemplateColumns={{ base: "1fr", md: "repeat(3, minmax(0, 1fr))" }} gap="4" mt="5"><Card.Root><Card.Header><HStack><Users/><Card.Title>Active roster</Card.Title></HStack></Card.Header><Card.Body><Box textStyle="4xl" fontWeight="bold">{data.snapshot()?.players.filter((item) => item.active).length ?? 0}</Box><Text color="fg.muted">players ready for selection</Text></Card.Body></Card.Root><Card.Root><Card.Header><HStack><Clock3/><Card.Title>Published plans</Card.Title></HStack></Card.Header><Card.Body><Box textStyle="4xl" fontWeight="bold">{published().length}</Box><Text color="fg.muted">games count toward season totals</Text></Card.Body></Card.Root><Card.Root><Card.Header><HStack><Trophy/><Card.Title>Season</Card.Title></HStack></Card.Header><Card.Body><Box textStyle="2xl" fontWeight="bold">{data.snapshot()?.seasonName}</Box><Text color="fg.muted">single-team coaching workspace</Text></Card.Body></Card.Root></Grid>
    <Card.Root mt="5"><Card.Header><Card.Title>Planned season minutes</Card.Title><Card.Description>Published assignments only; live substitutions never change these totals.</Card.Description></Card.Header><Card.Body><Grid gridTemplateColumns={{ base: "1fr", sm: "repeat(2,1fr)", lg: "repeat(3,1fr)" }} gap="3"><For each={data.snapshot()?.players.filter((p) => p.active)}>{(player) => <HStack justifyContent="space-between" p="3" bg="bg.muted" borderRadius="l2"><HStack><Box display="grid" placeItems="center" bg="grass.solid.bg" color="grass.solid.fg" borderRadius="full" boxSize="9" fontWeight="bold">{player.jerseyNumber ?? "—"}</Box><Text fontWeight="medium">{player.displayName}</Text></HStack><Text fontWeight="bold">{totalMinutes(player.id)} min</Text></HStack>}</For></Grid></Card.Body></Card.Root>
  </>;
}
