import { A, useNavigate, useParams } from "@solidjs/router";
import { createStore } from "solid-js/store";
import { For, Show, createSignal } from "solid-js";
import { ArrowRight, CalendarCheck, MapPin, Pencil, Trash2 } from "lucide-solid";
import { Button, Card, Field, Input, SimpleDialog, Text } from "~/components/ui";
import { useSoccerData } from "~/features/soccer/SoccerDataProvider";
import { TOTAL_ASSIGNMENTS } from "~/lib/soccer/fixed-game";
import { Box, Grid, HStack, VStack } from "styled-system/jsx";
import { PageHeader } from "./PageHeader";

const localDateTime = (date = new Date(Date.now() + 7 * 86_400_000)) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
export function NewGamePage() {
  const data = useSoccerData(); const navigate = useNavigate(); const [pending, setPending] = createSignal(false);
  const [draft, setDraft] = createStore({ opponentName: "", venueName: "", venueAddress: "", startsAt: localDateTime(), arrivalAt: localDateTime(new Date(Date.now() + 7 * 86_400_000 - 45 * 60_000)) });
  const save = async () => { setPending(true); const result = await data.run("createGame", { ...draft }) as { gameId?: string }; setPending(false); if (result?.gameId) navigate(`/games/${result.gameId}`); };
  return <><PageHeader eyebrow="Schedule" title="Plan a new game" description="Add the match logistics first. Every active player begins with unknown availability."/><Card.Root maxW="3xl"><Card.Body><Grid gridTemplateColumns={{ base: "1fr", md: "1fr 1fr" }} gap="4"><Field.Root required><Field.Label>Opponent</Field.Label><Input value={draft.opponentName} onInput={(e) => setDraft("opponentName", e.currentTarget.value)} /></Field.Root><Field.Root required><Field.Label>Venue</Field.Label><Input value={draft.venueName} onInput={(e) => setDraft("venueName", e.currentTarget.value)} /></Field.Root><Field.Root><Field.Label>Venue address</Field.Label><Input value={draft.venueAddress} onInput={(e) => setDraft("venueAddress", e.currentTarget.value)} /></Field.Root><Box/><Field.Root required><Field.Label>Game start</Field.Label><Input type="datetime-local" value={draft.startsAt} onInput={(e) => setDraft("startsAt", e.currentTarget.value)} /></Field.Root><Field.Root><Field.Label>Arrival time</Field.Label><Input type="datetime-local" value={draft.arrivalAt} onInput={(e) => setDraft("arrivalAt", e.currentTarget.value)} /></Field.Root></Grid></Card.Body><Card.Footer><HStack><Button variant="outline" onClick={() => navigate("/")}>Cancel</Button><Button loading={pending()} disabled={!draft.opponentName || !draft.venueName} onClick={save}>Create game <ArrowRight size={16}/></Button></HStack></Card.Footer></Card.Root></>;
}

export function GameDetailPage() {
  const data = useSoccerData(); const params = useParams(); const navigate = useNavigate();
  const [editOpen, setEditOpen] = createSignal(false); const [editDraft, setEditDraft] = createStore({ opponentName: "", venueName: "", venueAddress: "", startsAt: "", arrivalAt: "" });
  const game = () => data.snapshot()?.games.find((item) => item.id === params.gameId);
  const availability = () => data.snapshot()?.availability.filter((item) => item.gameId === params.gameId) ?? [];
  const count = (status: "unknown" | "available" | "unavailable") => availability().filter((item) => item.status === status).length;
  const canBuildSchedule = () => count("unknown") === 0 && count("available") >= 7;
  const targetMinutes = () => count("available") ? Math.round(TOTAL_ASSIGNMENTS * 7 / count("available")) : 0;
  const openEditor = () => { const current = game(); if (!current) return; setEditDraft({ opponentName: current.opponentName, venueName: current.venueName, venueAddress: current.venueAddress ?? "", startsAt: localDateTime(new Date(current.startsAt)), arrivalAt: current.arrivalAt ? localDateTime(new Date(current.arrivalAt)) : "" }); setEditOpen(true); };
  const saveGame = async () => { const current = game(); if (!current) return; await data.run("updateGame", { id: current.id, ...editDraft }); setEditOpen(false); };
  return <Show when={game()}>{(current) => <><PageHeader eyebrow="Game plan" title={`vs. ${current().opponentName}`} description={`${new Date(current().startsAt).toLocaleString([], { weekday: "long", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" })} · ${current().venueName}`} actions={<HStack flexWrap="wrap"><Show when={canBuildSchedule()} fallback={<Button disabled><CalendarCheck size={16}/> Build schedule</Button>}><A href={`/games/${current().id}/schedule`}><Button><CalendarCheck size={16}/> Build schedule</Button></A></Show><Button variant="outline" onClick={openEditor}><Pencil size={16}/> Edit game</Button><Button variant="plain" colorPalette="red" onClick={() => { void data.run("deleteGame", { id: current().id }).then(() => navigate("/")); }}><Trash2 size={16}/> Delete game</Button></HStack>}/>
    <Grid gridTemplateColumns={{ base: "1fr", lg: "2fr 1fr" }} gap="5"><Card.Root><Card.Header><Card.Title>Player availability</Card.Title><Card.Description>Resolve every player before generating a schedule.</Card.Description></Card.Header><Card.Body><VStack gap="2" alignItems="stretch"><For each={data.snapshot()?.players.filter((p) => p.active)}>{(player) => { const item = () => availability().find((entry) => entry.playerId === player.id); return <HStack justifyContent="space-between" p="3" borderWidth="1px" borderColor="border" borderRadius="l2"><HStack><Box boxSize="9" display="grid" placeItems="center" borderRadius="full" bg="bg.muted" fontWeight="bold">{player.jerseyNumber ?? "—"}</Box><Text fontWeight="medium">{player.displayName}</Text></HStack><HStack gap="1"><For each={["available", "unavailable", "unknown"] as const}>{(status) => <Button size="sm" variant={item()?.status === status ? "solid" : "outline"} colorPalette={status === "available" ? "grass" : status === "unavailable" ? "red" : "gray"} onClick={() => data.run("setAvailability", { gameId: current().id, playerId: player.id, status })}>{status === "available" ? "In" : status === "unavailable" ? "Out" : "?"}</Button>}</For></HStack></HStack>; }}</For></VStack></Card.Body><Card.Footer><Show when={count("unknown") > 0}><Button variant="outline" onClick={() => data.run("markAllAvailable", { gameId: current().id })}>Mark remaining available</Button></Show></Card.Footer></Card.Root>
    <VStack gap="4" alignItems="stretch"><Card.Root><Card.Header><Card.Title>Capacity</Card.Title></Card.Header><Card.Body><VStack alignItems="stretch" gap="3"><HStack justifyContent="space-between"><Text color="fg.muted">Available</Text><Text fontWeight="bold">{count("available")}</Text></HStack><HStack justifyContent="space-between"><Text color="fg.muted">Unknown</Text><Text fontWeight="bold">{count("unknown")}</Text></HStack><HStack justifyContent="space-between"><Text color="fg.muted">Field assignments</Text><Text fontWeight="bold">56</Text></HStack><HStack justifyContent="space-between"><Text color="fg.muted">Target / player</Text><Text fontWeight="bold">~{targetMinutes()} min</Text></HStack></VStack></Card.Body></Card.Root><Show when={!canBuildSchedule()}><Card.Root><Card.Body><Text color="fg.muted">Resolve availability and keep at least seven players available to build the rotation.</Text></Card.Body></Card.Root></Show><Card.Root><Card.Body><HStack><MapPin/><VStack alignItems="start" gap="0"><Text fontWeight="medium">{current().venueName}</Text><Text textStyle="sm" color="fg.muted">{current().venueAddress || "No street address"}</Text></VStack></HStack></Card.Body></Card.Root></VStack></Grid><SimpleDialog open={editOpen()} onOpenChange={setEditOpen} title="Edit game" footer={<HStack><Button variant="outline" onClick={() => setEditOpen(false)}>Cancel</Button><Button onClick={saveGame}>Save game</Button></HStack>}><Grid gridTemplateColumns={{ base: "1fr", md: "1fr 1fr" }} gap="4"><Field.Root required><Field.Label>Opponent</Field.Label><Input value={editDraft.opponentName} onInput={(event) => setEditDraft("opponentName", event.currentTarget.value)}/></Field.Root><Field.Root required><Field.Label>Venue</Field.Label><Input value={editDraft.venueName} onInput={(event) => setEditDraft("venueName", event.currentTarget.value)}/></Field.Root><Field.Root><Field.Label>Venue address</Field.Label><Input value={editDraft.venueAddress} onInput={(event) => setEditDraft("venueAddress", event.currentTarget.value)}/></Field.Root><Box/><Field.Root required><Field.Label>Game start</Field.Label><Input type="datetime-local" value={editDraft.startsAt} onInput={(event) => setEditDraft("startsAt", event.currentTarget.value)}/></Field.Root><Field.Root><Field.Label>Arrival time</Field.Label><Input type="datetime-local" value={editDraft.arrivalAt} onInput={(event) => setEditDraft("arrivalAt", event.currentTarget.value)}/></Field.Root></Grid></SimpleDialog></> }</Show>;
}
